# Generated by Django 3.1.1 on 2021-10-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211001_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='is_group_conversation',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
